import type { Metadata } from "next";
import "./globals.css";
import { Providers } from './providers'
import { fonts } from './fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={fonts.inter.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}